### PR TITLE
Quest/PeopleSoft Support

### PR DESCRIPTION
**Pull request by nwestbury**
With this PR, University of Waterloo support for their class system "Quest" should work in addition to University of Alberta "Beartracks" by specifying the university shorthand (e.g. "uwaterloo" or "ualberta") in the `credentials.json`. It should be easy to extend this to other PeopleSoft-based university sign-ups (but still hard for general university signups).

The main change is just moving all DOM identifier constants to a separate json file `config.json` custom for each university. 

Before merging please:
- Ensure I did not break Breaktrack watchlist (I can't test this without an active account)
- Update the encrypted `credentials.json.enc` to have a "university" field (I don't know how to open this).
- Consider renaming the repo to reflect this (might mess with Travis) 
- Let me know of any other improvements you want to this PR

Do not hesitate to ask for clarifications or questions. Thanks!

### CODE REVIEW

**Comment by nwestbury** [comment]
Since this PR was created, [Quest was updated](https://uwaterloo.ca/information-systems-technology/news/quest-unavailable-february-16-22-scheduled-upgrade) which broke this, will fix at some point.

**Comment by nlieb** [comment]
What broke about it? And can you create a regression test

**Comment by nwestbury** [comment]
They added a two-step login where you click on a link before gaining access to the login screen. As far as I can tell, there is no direct link to the login [see here](https://quest.pecs.uwaterloo.ca/psp/SS/ACADEMIC/SA/?cmd=login&languageCd=ENG).

Fixing this is non-trivial (but still easy) because I think it will require refactoring to add Quest-specific actions (e.g. navigateLogin). This will probably be need to done to extend to other universities anyways. The way I think to do this is to add a property that's an array of actions for each university something like:

`{
   "ualberta": {
        "actions": ["login", "enroll"],
        [...]
   },
   "uwaterloo": {
        "actions": ["navigateLogin", "login", "enroll"],
        [...]
   }
}`

And then each process will iterate over the university's actions (which will map to the functions we have). Feel free to ask clarification questions but I'm open to a different approach if you have suggestions.

**Comment by nlieb** [comment]
That's starting to look like a sketchy DSL. What do you think about just
having a rigid api and a swappable plugin for each uni that's just plain
code.

For example, we could just have a separate login function for each uni,
maybe with some common util functions.

On Mar 16, 2018 12:24 AM, "Nico" <notifications@github.com> wrote:

They added a two-step login where you click on a link before gaining access
to the login screen. As far as I can tell, there is no direct link to the
login see here
<https://quest.pecs.uwaterloo.ca/psp/SS/ACADEMIC/SA/?cmd=login&languageCd=ENG>
.

Fixing this is non-trivial (but still easy) because I think it will require
refactoring to add Quest-specific actions (e.g. navigateLogin). This will
probably be need to done to extend to other universities anyways. The way I
think to do this is to add a property that's an array of actions for each
university something like:

{ "ualberta": { "actions": ["login", "enroll"], [...] }, "uwaterloo": {
"actions": ["navigateLogin", "login", "enroll"], [...] } }

And then each process will iterate over the university's actions (which
will map to the functions we have). Feel free to ask clarification
questions but I'm open to a different approach if you have suggestions.

—
You are receiving this because your review was requested.

Reply to this email directly, view it on GitHub
<https://github.com/nlieb/ualberta-enroll/pull/1#issuecomment-373615262>,
or mute the thread

**Comment by nwestbury** [comment]
> What do you think about just having a rigid api and a swappable plugin for each uni that's just plain code?

That'd work but my concern is there is going to be massive code overlap university-to-university so we'll be rewriting stuff a lot of the same stuff. For example, uwaterloo/ualberta differ just in this one step.

**Comment by nlieb** [comment]
Yea but at the same time most of the code is table parsing and whatnot
which can be extracted into a mega parser util. The main loop could also be
it's own class with dependency injection, etc. Notifications in one
class... Plus if we have a rigid api it's more easily unit testable.

Having these actions in JSON just seems like it can get out of hand quickly


On Mar 16, 2018 12:45 AM, "Nico" <notifications@github.com> wrote:

What do you think about just having a rigid api and a swappable plugin for
each uni that's just plain code?

That'd work but my concern is there is going to be massive code overlap
university-to-university so we'll be rewriting stuff a lot of the same
stuff. For example, uwaterloo/ualberta differ just in this one step.

—
You are receiving this because your review was requested.

Reply to this email directly, view it on GitHub
<https://github.com/nlieb/ualberta-enroll/pull/1#issuecomment-373618391>,
or mute the thread

**Comment by nwestbury** [comment]
> Having these actions in JSON just seems like it can get out of hand quickly

So is writing a custom function for each university though. If I understand what you're suggesting it'll roughly amount to the same thing but with more flexibility at the cost of modularity. Nonetheless, I think this is probably a fine approach so long as functions are broken down a little more so they can be reused (e.g. separate the "goto login page" from the "login").

> Yea but at the same time most of the code is table parsing and whatnot
which can be extracted into a mega parser util. The main loop could also be
it's own class with dependency injection, etc. Notifications in one
class... Plus if we have a rigid api it's more easily unit testable.

Could you create a sample class I can use as a template? I'm not totally clear on how the dependency injection will work.. do you want a separate loginClass for each type of university login or just custom member function of a loginClass? If you could get ualberta working with this class system, I'll emulate it for uwaterloo.

**Pull request closed without merging**
